name: Build Docker Image and push DockerHub

on:
  push:
    branches: [ "main" ]


jobs:

  build:


    runs-on: ubuntu-latest
 

    steps:
    - uses: actions/checkout@v3
    - name: Scripts
      run: | 
        
        docker build . --tag targaryen1199/go_image232:$(date +%s)
        docker login ${{secrets.DOCKER_USER}}/targaryen1199/go_image232:latest
        docker push targaryen1199/go_image232:latest
        
        

