name: Build Docker Image and push DockerHub

on:
  push:
    branches: [ "main" ]


jobs:
  test_the_action:
    if: "contains(github.event.head_commit.message, 'yes')"
     
    runs-on: ubuntu-latest
 

    steps:
    - uses: actions/checkout@v3
    - name: Scripts
      run: | 
        
        docker build -t app .
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        docker tag app ${{secrets.DOCKER_USER}}/go_image232:$(date +%s)
        docker push ${{secrets.DOCKER_USER}}/go_image232
        
        

